# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 06:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('messageManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='to_who',
        ),
    ]
